### ISSUE TITLE
running it on single machine

### ISSUE THREAD

**Issue by hlsafin** [kakaobrain/brain_agent#1]
Can I run this on a single GPU machine; and if so, I presume it will take forever?

**Comment by seungeunrho** [comment]
Sure. It can run on a single GPU, but it takes a long time to fully train the model.
Here, fully training means training with 20B frames.
Instead, training only 1B frames with one V100 GPU takes about 4 days.

**Comment by hlsafin** [comment]
Oh okay great, thank you. I also have a question, do you think this approach could also do well with minigrid problem or montezuma's revenge where rewards are sparse? 
Thank you.

**Comment by twidddj** [comment]
@hlsafin For now, this repo produces IMPALA based agent and it may not work well such tasks without additional learning signals such as _intrinsic reward_. You can find such result in page 8 of [this paper](https://arxiv.org/abs/2006.12122).

**Comment by hlsafin** [comment]
Is the additional learning signal hurt on tasks where it's more reactive than exploratory?
